// Copyright (c) 2015 Intel Corporation. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Iotivity API
namespace iotivity {

    //*************************************************************************
    // 1:1 mapping
    //*************************************************************************
    dictionary IotivityEleven {
    };

    interface Functions {
      [nodoc] static IotivityEleven IotivityElevenConstructor(
          DOMString objectId);
    }; 
};
